# Locate libgdata
#
# Created by Kai Dombrowe.


INCLUDE(FindPkgConfig)

IF ( LibGData_FIND_REQUIRED )
	SET( _pkgconfig_REQUIRED "REQUIRED" )
ELSE( LibGData_FIND_REQUIRED )
	SET( _pkgconfig_REQUIRED "" )	
ENDIF ( LibGData_FIND_REQUIRED )


PKG_SEARCH_MODULE(LIBGDATA "libgdata")


# set variables
IF (LIBGDATA_FOUND)
	SET(LIBGDATA_INCLUDE_DIRS ${LIBGDATA_INCLUDE_DIRS} CACHE INTERNAL "")
	SET(LIBGDATA_LIBRARIES ${LIBGDATA_LIBRARIES} CACHE INTERNAL "")
	SET(LIBGDATA_LIBRARY_DIRS ${LIBGDATA_LIBRARY_DIRS} CACHE INTERNAL "")
	SET(LIBGDATA_VERSION ${LIBGDATA_VERSION} CACHE INTERNAL "")
ENDIF ( LIBGDATA_FOUND )

# Hide advanced variables
MARK_AS_ADVANCED(LIBGDATA_LIBRARIES LIBGDATA_INCLUDE_DIRS)

